### ISSUE TITLE
Investigate failure in power/storms intersection

### ISSUE THREAD

**Issue by thomas-fred** [nismod/open-gira#77]
I think this was from running: `snakemake --cores all intersect_all`

```
Traceback (most recent call last):
  File "/home/fred/open-gira/.snakemake/scripts/tmpyhiq8fs6.intersect_4_gdploss.py", line 834, in <module>
    edges_affected_frag.to_file(
  File "/home/fred/anaconda3/envs/open-gira/lib/python3.9/site-packages/geopandas/geodataframe.py", line 1114, in to_file
    _to_file(self, filename, driver, schema, index, **kwargs)
  File "/home/fred/anaconda3/envs/open-gira/lib/python3.9/site-packages/geopandas/io/file.py", line 367, in _to_file
    schema = infer_schema(df)
  File "/home/fred/anaconda3/envs/open-gira/lib/python3.9/site-packages/geopandas/io/file.py", line 428, in infer_schema
    raise ValueError("Cannot write empty DataFrame to file.")
ValueError: Cannot write empty DataFrame to file.
[Mon Jul 11 16:36:03 2022]
Error in rule intersect_damages:
    jobid: 10231
    output: results/power_intersection/storm_data/individual_storms/NA/0/storm_0_271_5/25/storm_rNA_s0_n0_271_5.txt, results/power_intersection/storm_data/individual_storms/NA/0/storm_0_271_5/20/storm_rNA_s0_n0_271_5.txt, results/power_intersection/storm_data/individual_storms/NA/0/storm_0_271_5/30/storm_rNA_s0_n0_271_5.txt

RuleException:
CalledProcessError in line 77 of /home/fred/open-gira/workflow/rules/intersect/gdp-loss.smk:
Command 'set -euo pipefail;  /home/fred/anaconda3/envs/open-gira/bin/python /home/fred/open-gira/.snakemake/scripts/tmpyhiq8fs6.intersect_4_gdploss.py' returned non-zero exit status 1.
  File "/home/fred/open-gira/workflow/rules/intersect/gdp-loss.smk", line 77, in __rule_intersect_damages
  File "/home/fred/anaconda3/envs/open-gira/lib/python3.9/concurrent/futures/thread.py", line 58, in run
Removing output files of failed job intersect_damages since they might be corrupted:
results/power_intersection/storm_data/individual_storms/NA/0/storm_0_271_5/25/storm_rNA_s0_n0_271_5.txt
```

**Comment by thomas-fred** [comment]
Upgrading from geopandas 0.10.2 -> 0.11.0 allows one to write empty dataframes.

**Comment by thomas-fred** [comment]
After upgrading geopandas, a subsequent bug:
```
/home/fred/open-gira/.snakemake/scripts/tmppl0mrsp0.process_power_4_network.py:108: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  nodes = plants.append(targets).reset_index(drop=True)  # sources and targets located
box_957: creating network
/home/fred/anaconda3/envs/open-gira/lib/python3.9/site-packages/pandas/core/dtypes/cast.py:122: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  arr = construct_1d_object_array_from_listlike(values)
DOM population progress:  55%|██████████████████████████████████████████████████████████▉                                                 | 709/1298 [00:23<00:14, 41.48it/s]Traceback (most recent call last):
  File "/home/fred/open-gira/.snakemake/scripts/tmppl0mrsp0.process_power_4_network.py", line 172, in <module>
    network = snkit.network.link_nodes_to_nearest_edge(
  File "/home/fred/anaconda3/envs/open-gira/lib/python3.9/site-packages/snkit/network.py", line 338, in link_nodes_to_nearest_edge
    edge = nearest_edge(node.geometry, network.edges)
  File "/home/fred/anaconda3/envs/open-gira/lib/python3.9/site-packages/snkit/network.py", line 531, in nearest_edge
    return nearest(point, edges)
  File "/home/fred/anaconda3/envs/open-gira/lib/python3.9/site-packages/snkit/network.py", line 536, in nearest
    match_idx = gdf.sindex.nearest(geom, return_all=False)[1][0]
  File "/home/fred/anaconda3/envs/open-gira/lib/python3.9/site-packages/pandas/core/generic.py", line 5575, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'sindex'
```

Looks like snkit is trying to use a GeoDataFrame method (sindex) on what's actually a pandas DataFrame.

**Comment by thomas-fred** [comment]
See #80 for potential remedy.
